name: shellcheck

on:
  push:
    paths-ignore:
      - '.github/workflows/*'
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint check
        uses: azohra/shell-linter@latest
        with:
          path: "getssl"
